[webserver]
port = 9999

[logging]
level = 5 #Debug

[database]
username = "root"
password = "Raja@235"
dbname = "shoppinglist"
ip = "localhost"
port = 3306
max_connection_attempt = 10

[kv]
#ip = "redis"
ip = "127.0.0.1:9675"